// +-------------------------------------------------------------------------
//
//   Rust C64 Emulator - Rust 6510 元数据生成器
//
//   文件:       generateRustCpuMetadata.ts
//
//   创建日期:   2026年08月10日
//   作者:       OpenAI Codex
// --------------------------------------------------------------------------

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import {
  CPU_ADDRESS_MODE,
  CPU_ADDRESS_MODE_LENGTH,
  CPU_CYCLE_TEMPLATE,
  CPU_CYCLE_TEMPLATE_BASE_CYCLES,
  CPU_MEMORY_ACCESS,
  CPU_OPCODE_FLAG,
  CPU_OPCODE_FLAGS,
  CPU_OPCODE_OPERATION,
  CPU_OPCODE_PLAN,
  CPU_OPCODE_PLAN_ACCESS_MASK,
  CPU_OPCODE_PLAN_ACCESS_SHIFT,
  CPU_OPCODE_PLAN_MODE_MASK,
  CPU_OPCODE_PLAN_MODE_SHIFT,
  CPU_OPCODE_PLAN_PAGE_RULE_MASK,
  CPU_OPCODE_PLAN_PAGE_RULE_SHIFT,
  CPU_OPCODE_PLAN_TEMPLATE_MASK,
  CPU_OPERATION,
  CPU_PAGE_RULE,
} from '../src/core/cpu/CpuOpcodeMetadata';

const OUTPUT_PATH = fileURLToPath(
  new URL('../crates/c64-core/src/cpu_generated.rs', import.meta.url),
);
const CHECK_ONLY = process.argv.includes('--check');

function renderConstantModule(
  moduleName: string,
  constants: Readonly<Record<string, number>>,
): string {
  const definitions = Object.entries(constants)
    .sort((left, right) => left[1] - right[1])
    .map(([name, value]) => `    pub const ${name}: u8 = ${value};`);
  return [`pub mod ${moduleName} {`, ...definitions, '}', ''].join('\n');
}

function renderArray(
  name: string,
  rustType: 'u8' | 'u16',
  values: Uint8Array | Uint16Array,
): string {
  const width = rustType === 'u8' ? 2 : 4;
  const valuesPerLine = rustType === 'u8' ? 16 : 12;
  const lines: string[] = [];
  for (let offset = 0; offset < values.length; offset += valuesPerLine) {
    const chunk = Array.from(values.slice(offset, offset + valuesPerLine));
    lines.push(
      `    ${chunk.map((value) => `0x${value.toString(16).padStart(width, '0')}`).join(', ')},`,
    );
  }
  return [
    '#[rustfmt::skip]',
    `pub const ${name}: [${rustType}; ${values.length}] = [`,
    ...lines,
    '];',
    '',
  ].join('\n');
}

function renderRustSource(): string {
  return [
    '// +-------------------------------------------------------------------------',
    '//',
    '//   Rust C64 Emulator - 由 TypeScript 规范生成的 6510 元数据',
    '//',
    '//   文件:       cpu_generated.rs',
    '//',
    '//   创建日期:   2026年08月10日',
    '//   作者:       OpenAI Codex',
    '// --------------------------------------------------------------------------',
    '// @generated by tools/generateRustCpuMetadata.ts; do not edit by hand.',
    '',
    renderConstantModule('operation', CPU_OPERATION),
    renderConstantModule('cycle_template', CPU_CYCLE_TEMPLATE),
    renderConstantModule('address_mode', CPU_ADDRESS_MODE),
    renderConstantModule('memory_access', CPU_MEMORY_ACCESS),
    renderConstantModule('page_rule', CPU_PAGE_RULE),
    renderConstantModule('opcode_flag', CPU_OPCODE_FLAG),
    `pub const OPCODE_PLAN_TEMPLATE_MASK: u16 = 0x${CPU_OPCODE_PLAN_TEMPLATE_MASK.toString(16).padStart(4, '0')};`,
    `pub const OPCODE_PLAN_MODE_SHIFT: u32 = ${CPU_OPCODE_PLAN_MODE_SHIFT};`,
    `pub const OPCODE_PLAN_MODE_MASK: u16 = 0x${CPU_OPCODE_PLAN_MODE_MASK.toString(16).padStart(4, '0')};`,
    `pub const OPCODE_PLAN_ACCESS_SHIFT: u32 = ${CPU_OPCODE_PLAN_ACCESS_SHIFT};`,
    `pub const OPCODE_PLAN_ACCESS_MASK: u16 = 0x${CPU_OPCODE_PLAN_ACCESS_MASK.toString(16).padStart(4, '0')};`,
    `pub const OPCODE_PLAN_PAGE_RULE_SHIFT: u32 = ${CPU_OPCODE_PLAN_PAGE_RULE_SHIFT};`,
    `pub const OPCODE_PLAN_PAGE_RULE_MASK: u16 = 0x${CPU_OPCODE_PLAN_PAGE_RULE_MASK.toString(16).padStart(4, '0')};`,
    '',
    renderArray('OPCODE_OPERATION', 'u8', CPU_OPCODE_OPERATION),
    renderArray('OPCODE_PLAN', 'u16', CPU_OPCODE_PLAN),
    renderArray('OPCODE_FLAGS', 'u8', CPU_OPCODE_FLAGS),
    renderArray('CYCLE_TEMPLATE_BASE_CYCLES', 'u8', CPU_CYCLE_TEMPLATE_BASE_CYCLES),
    renderArray('ADDRESS_MODE_LENGTH', 'u8', CPU_ADDRESS_MODE_LENGTH),
  ].join('\n');
}

const expected = renderRustSource();
if (CHECK_ONLY) {
  let actual: string;
  try {
    actual = await readFile(OUTPUT_PATH, 'utf8');
  } catch (error: unknown) {
    throw new Error('Rust CPU metadata is missing; run npm run generate:rust-cpu.', {
      cause: error,
    });
  }
  if (actual !== expected) {
    throw new Error('Rust CPU metadata is stale; run npm run generate:rust-cpu.');
  }
  console.log('PASS Rust 6510 metadata exactly matches the TypeScript architecture table.');
} else {
  await writeFile(OUTPUT_PATH, expected, 'utf8');
  console.log(`Generated ${OUTPUT_PATH}.`);
}
