// +-------------------------------------------------------------------------
//
//   Rust C64 Emulator - Rust SID combined-waveform table generator
//
//   File:       generateRustSidWaveforms.ts
//
//   Created:    2026-08-11
//   Author:     OpenAI Codex
// --------------------------------------------------------------------------

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import {
  SID_6581_PULSE_SAW_DATA,
  SID_6581_PULSE_SAW_TRIANGLE_DATA,
  SID_6581_PULSE_TRIANGLE_DATA,
  SID_6581_TRIANGLE_SAW_DATA,
  SID_8580_PULSE_SAW_DATA,
  SID_8580_PULSE_SAW_TRIANGLE_DATA,
  SID_8580_PULSE_TRIANGLE_DATA,
  SID_8580_TRIANGLE_SAW_DATA,
} from '../src/devices/SidCombinedWaveformData';

const OUTPUT_PATH = fileURLToPath(
  new URL('../crates/c64-core/src/devices/sid/waveform_data.rs', import.meta.url),
);
const CHECK_ONLY = process.argv.includes('--check');
const SAMPLE_COUNT = 1 << 12;

const TABLES = [
  ['SID_6581_TRIANGLE_SAW', SID_6581_TRIANGLE_SAW_DATA],
  ['SID_6581_PULSE_TRIANGLE', SID_6581_PULSE_TRIANGLE_DATA],
  ['SID_6581_PULSE_SAW', SID_6581_PULSE_SAW_DATA],
  ['SID_6581_PULSE_SAW_TRIANGLE', SID_6581_PULSE_SAW_TRIANGLE_DATA],
  ['SID_8580_TRIANGLE_SAW', SID_8580_TRIANGLE_SAW_DATA],
  ['SID_8580_PULSE_TRIANGLE', SID_8580_PULSE_TRIANGLE_DATA],
  ['SID_8580_PULSE_SAW', SID_8580_PULSE_SAW_DATA],
  ['SID_8580_PULSE_SAW_TRIANGLE', SID_8580_PULSE_SAW_TRIANGLE_DATA],
] as const;

function decode(encoded: string, name: string): Uint8Array {
  const bytes = new Uint8Array(Buffer.from(encoded, 'base64'));
  if (bytes.length !== SAMPLE_COUNT) {
    throw new RangeError(`${name} contains ${bytes.length} samples; expected ${SAMPLE_COUNT}.`);
  }
  return bytes;
}

function renderTable(name: string, encoded: string): string {
  const bytes = decode(encoded, name);
  const lines: string[] = [];
  for (let offset = 0; offset < bytes.length; offset += 24) {
    const values = Array.from(bytes.slice(offset, offset + 24));
    lines.push(
      `    ${values.map((value) => `0x${value.toString(16).padStart(2, '0')}`).join(', ')},`,
    );
  }
  return [
    '#[rustfmt::skip]',
    `pub(super) const ${name}: [u8; ${SAMPLE_COUNT}] = [`,
    ...lines,
    '];',
    '',
  ].join('\n');
}

function renderSource(): string {
  return [
    '// +-------------------------------------------------------------------------',
    '//',
    '//   Rust C64 Emulator - generated reSID combined-waveform samples',
    '//',
    '//   File:       sid/waveform_data.rs',
    '//',
    '//   Created:    2026-08-11',
    '//   Author:     OpenAI Codex',
    '// --------------------------------------------------------------------------',
    '// @generated by tools/generateRustSidWaveforms.ts; do not edit by hand.',
    '',
    ...TABLES.map(([name, encoded]) => renderTable(name, encoded)),
  ].join('\n');
}

const expected = renderSource();
if (CHECK_ONLY) {
  let actual: string;
  try {
    actual = await readFile(OUTPUT_PATH, 'utf8');
  } catch (error: unknown) {
    throw new Error('Rust SID waveform tables are missing; run npm run generate:rust-sid.', {
      cause: error,
    });
  }
  if (actual !== expected) {
    throw new Error('Rust SID waveform tables are stale; run npm run generate:rust-sid.');
  }
  console.log('PASS Rust SID waveform tables exactly match the pinned TypeScript/reSID samples.');
} else {
  await writeFile(OUTPUT_PATH, expected, 'utf8');
  console.log(`Generated ${OUTPUT_PATH}.`);
}
